// <auto-generated />
namespace CRMS.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class CommonLook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommonLook));
        
        string IMigrationMetadata.Id
        {
            get { return "202303170443306_CommonLook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
